### ISSUE TITLE
How to set cache timeout for InMemoryCaches?

### ISSUE THREAD

**Issue by Bouni** [comeuplater/fastapi_cache#6]
I want to use InMemoryCache, is there a way to define a cache timeout when the cache gets invalid and needs to get refreshed?

**Comment by comeuplater** [comment]
Initially InMemoryCache is planned for test purposes. You can create your own cache backend based on [expiringdict](https://pypi.org/project/expiringdict/). I will add that in new version.

**Comment by Bouni** [comment]
Ok, then I'll wait for the next version. Thanks!
